pipeline{
  
  agent any
    stages
    {
        stage('Build')
        {
            steps
            {
             echo "kartik beta mera hai"
             withMaven(maven : 'apache.maven.3.6.3')
             {
                 sh 'mvn clean'
                 sh 'mvn package'

             }

            }
        }
    }

}