pipeline{
  
  agent any
    stages
    {
        stage('Build')
        {
            steps
            {
              maven 'Maven-3.6.3'
              
                  echo "building..."
                  sh 'mvn clean'
                  sh 'mvn package'
              

            }
        }
    }

}