pipeline{
  
  agent any
    stages
    {
        stage('Build')
        {
            steps
            {
             echo "kartik beta mera hai"
             withMaven
             {
                 sh "mvn clean"
                 sh "mvn package"

             }

            }
        }
    }

}